package pojo;
// Generated 2014-3-18 15:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.LinkedHashSet;
import java.util.Set;

/**
 * MachineType generated by hbm2java
 */
public class MachineType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer sum;
	private Set machines = new LinkedHashSet(0);

	public MachineType() {
	}

	public MachineType(String name) {
		this.name = name;
	}

	public MachineType(String name, Integer sum, Set machines) {
		this.name = name;
		this.sum = sum;
		this.machines = machines;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSum() {
		return this.sum;
	}

	public void setSum(Integer sum) {
		this.sum = sum;
	}

	public Set getMachines() {
		return this.machines;
	}

	public void setMachines(Set machines) {
		this.machines = machines;
	}

}
