package pojo;
// Generated 2014-3-18 15:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Machine generated by hbm2java
 */
public class Machine implements java.io.Serializable {

	private Integer id;
	private Staff staff;
	private MachineType machineType;
	private String alias;
	
	//lazy fetch
	private Set plans = new HashSet(0);

	public Machine() {
	}

	public Machine(MachineType machineType, String alias) {
		this.machineType = machineType;
		this.alias = alias;
	}

	public Machine(Staff staff, MachineType machineType, String alias, Set plans) {
		this.staff = staff;
		this.machineType = machineType;
		this.alias = alias;
		this.plans = plans;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public MachineType getMachineType() {
		return this.machineType;
	}

	public void setMachineType(MachineType machineType) {
		this.machineType = machineType;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public Set getPlans() {
		return this.plans;
	}

	public void setPlans(Set plans) {
		this.plans = plans;
	}

}
