package pojo;
// Generated 2014-3-18 15:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer sum;
	private String spec;
	
	//lazy fetch
	private Set plans = new HashSet(0);

	public Product() {
	}

	public Product(String name) {
		this.name = name;
	}

	public Product(String name, Integer sum, String spec, Set plans) {
		this.name = name;
		this.sum = sum;
		this.spec = spec;
		this.plans = plans;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSum() {
		return this.sum;
	}

	public void setSum(Integer sum) {
		this.sum = sum;
	}

	public String getSpec() {
		return this.spec;
	}

	public void setSpec(String spec) {
		this.spec = spec;
	}

	public Set getPlans() {
		return this.plans;
	}

	public void setPlans(Set plans) {
		this.plans = plans;
	}

}
