package pojo;
// Generated 2014-3-18 15:22:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer gender;
	private Integer age;
	
	//lazy fetch
	private Set machines = new HashSet(0);

	public Staff() {
	}

	public Staff(String name) {
		this.name = name;
	}

	public Staff(String name, Integer gender, Integer age, Set machines) {
		this.name = name;
		this.gender = gender;
		this.age = age;
		this.machines = machines;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Set getMachines() {
		return this.machines;
	}

	public void setMachines(Set machines) {
		this.machines = machines;
	}

}
